### ISSUE TITLE
Title font family

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/SamWebsite#1]

**Comment by samtous** [comment]
<style>
@import url('https://fonts.googleapis.com/css?family=Cousine:400,700|El+Messiri:400,500,600,700|Federo|Marmelad|Nunito+Sans:400,600,700,800|Philosopher:400,700|Poppins:400,500,600,700|Tenor+Sans|Yatra+One');
</style>

**Comment by Kallirroi** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/21959743/490a6a4e-da9f-11e6-829a-f7b94088537d.png)
Cousine

![image](https://cloud.githubusercontent.com/assets/10440556/21959744/54b6a222-da9f-11e6-8985-45002922bd32.png)
El Messiri

![image](https://cloud.githubusercontent.com/assets/10440556/21959747/60d4fb76-da9f-11e6-9e86-aa6173d916d3.png)
Federo

![image](https://cloud.githubusercontent.com/assets/10440556/21959749/6c179ade-da9f-11e6-9c86-5043336f2107.png)
Marmelad

![image](https://cloud.githubusercontent.com/assets/10440556/21959751/766fa6a2-da9f-11e6-9841-0d66d19397b3.png)
Nunito Sans

![image](https://cloud.githubusercontent.com/assets/10440556/21959755/8120877e-da9f-11e6-891b-ebe7405f8f69.png)
Philosopher

![image](https://cloud.githubusercontent.com/assets/10440556/21959758/8d0d333e-da9f-11e6-8d1e-429bf5271c63.png)
Poppins

![image](https://cloud.githubusercontent.com/assets/10440556/21959759/997b20e0-da9f-11e6-84d8-2bc9a28eafaa.png)
Tenor Sans

![image](https://cloud.githubusercontent.com/assets/10440556/21959761/a786d97c-da9f-11e6-84fc-a42d23c4a415.png)
Yatra One

**Comment by Kallirroi** [comment]
I like Cousine, Nunito and Yatra, even though its very Spiderman Comic-like
