### ISSUE TITLE
let's change the favicon

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/SamWebsite#13]

**Comment by Kallirroi** [comment]
@samtous can you make a PNG out of the 3D version of yourself (the one in the iframe) ? That'd be cool!

**Comment by samtous** [comment]
too narcissistic! maybe blue circle?

**Comment by Kallirroi** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/21959789/5f35bf16-daa0-11e6-8402-e1b31fb7ff64.png)

**Comment by Kallirroi** [comment]
I like the circle better!

**Comment by samtous** [comment]
yes, make it happen
