### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/SamWebsite#5]
Instead of the circle mouse pointer, let's make it a triangle, and when it's clickalbe it becomes a circle

**Comment by Kallirroi** [comment]
@samtous maybe we should make a new cursor that visually hints that the item can be dragged?

**Comment by samtous** [comment]
yes. try a square that's been rotated 45 deg., with an inscribed square in it that has been booleaned out? will look like 4 triangles arranged tip end to end

**Comment by samtous** [comment]
could be bigger?

**Comment by Kallirroi** [comment]
check now
