### ISSUE TITLE
box shadows

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/SamWebsite#7]
I'm wondering if the project page shadows should be black or if they should be blue

**Comment by Kallirroi** [comment]
@samtous all of them will have the shadow color?

**Comment by samtous** [comment]
not sure what the question is. they all have a shadow as it is. do you mean that all project page shadows should be blue? i guess?

**Comment by Kallirroi** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/21959634/d9f429c8-da9a-11e6-98d6-d51ac87ba960.png)

**Comment by Kallirroi** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/21959647/3000fc2e-da9b-11e6-9b7a-91b5fb43558a.png)

vs 

![image](https://cloud.githubusercontent.com/assets/10440556/21959648/3a2a8e9a-da9b-11e6-8875-9c8694613c60.png)

**Comment by samtous** [comment]
Let's stick with blue
